server:
  port: 8761
  shutdown: graceful
spring:
  application:
    name: discovery-service
  lifecycle:
    timeout-per-shutdown-phase: 20s
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      probes:
        enabled: true
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
